### ISSUE TITLE
usbipd: error: Server is currently not running.

### ISSUE THREAD

**Issue by watson8544** [dorssel/usbipd-win#122]
Please run with `usbipd server Logging:LogLevel:Default=Trace` for running usbipd server as windows Administrator mode in cmd.exe

_Originally posted by @dorssel in https://github.com/dorssel/usbipd-win/issues/96#issuecomment-968896352_

**Comment by watson8544** [comment]
If you meet the problem "usbipd: error: Server is currently not running", Please run with `usbipd server Logging:LogLevel:Default=Trace`

**Comment by m4l490n** [comment]
> If you meet the problem "usbipd: error: Server is currently not running", Please run with `usbipd server Logging:LogLevel:Default=Trace`

Do I have to do this every time? Isn't it supposed to start automatically?

**Comment by dorssel** [comment]
@m4l490n 
No, the service should start automatically on Windows boot. If it does not, please check the status in Windows Service manager. It should be set to "Automatic Start". If it is, and the service is not running, then please check the Windows Event Log, it should have an entry with a crash report on what went wrong. Please post it here.

**Comment by JohnBerg60** [comment]
Same problem here. Occurs after debugging with a STLINK-V2 device. After starting the ```USBIP Device Host``` in the Service mananger, I am back in business.

```
Log Name:      Application
Source:        usbipd-win
Date:          11-1-2022 18:26:23
Event ID:      3
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      JOHN-LEGION5
Description:
Category: UsbIpServer.ConnectedClient
EventId: 3

An exception occurred while communicating with the client:

Exception: 
System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine..
 ---> System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 )
   at UsbIpServer.Tools.ReadExactlyAsync(Stream stream, Memory`1 buf, CancellationToken cancellationToken) in D:\a\usbipd-win\usbipd-win\UsbIpServer\Tools.cs:line 23
   at UsbIpServer.Interop.UsbIp.ReadUsbIpHeaderAsync(Stream stream, CancellationToken cancellationToken) in D:\a\usbipd-win\usbipd-win\UsbIpServer\Interop\UsbIp.cs:line 184
   at UsbIpServer.AttachedClient.RunAsync(CancellationToken cancellationToken) in D:\a\usbipd-win\usbipd-win\UsbIpServer\AttachedClient.cs:line 477
   at UsbIpServer.ConnectedClient.HandleRequestImportAsync(CancellationToken cancellationToken) in D:\a\usbipd-win\usbipd-win\UsbIpServer\ConnectedClient.cs:line 207
   at UsbIpServer.ConnectedClient.HandleRequestImportAsync(CancellationToken cancellationToken) in D:\a\usbipd-win\usbipd-win\UsbIpServer\ConnectedClient.cs:line 228

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="usbipd-win" />
    <EventID Qualifiers="0">3</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2022-01-11T17:26:23.8625797Z" />
    <EventRecordID>10710</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>JOHN-LEGION5</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Category: UsbIpServer.ConnectedClient
EventId: 3

An exception occurred while communicating with the client:

Exception: 
System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine..
 ---&gt; System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource&lt;System.Int32&gt;.GetResult(Int16 )
   at UsbIpServer.Tools.ReadExactlyAsync(Stream stream, Memory`1 buf, CancellationToken cancellationToken) in D:\a\usbipd-win\usbipd-win\UsbIpServer\Tools.cs:line 23
   at UsbIpServer.Interop.UsbIp.ReadUsbIpHeaderAsync(Stream stream, CancellationToken cancellationToken) in D:\a\usbipd-win\usbipd-win\UsbIpServer\Interop\UsbIp.cs:line 184
   at UsbIpServer.AttachedClient.RunAsync(CancellationToken cancellationToken) in D:\a\usbipd-win\usbipd-win\UsbIpServer\AttachedClient.cs:line 477
   at UsbIpServer.ConnectedClient.HandleRequestImportAsync(CancellationToken cancellationToken) in D:\a\usbipd-win\usbipd-win\UsbIpServer\ConnectedClient.cs:line 207
   at UsbIpServer.ConnectedClient.HandleRequestImportAsync(CancellationToken cancellationToken) in D:\a\usbipd-win\usbipd-win\UsbIpServer\ConnectedClient.cs:line 228
</Data>
  </EventData>
</Event>
```

**Comment by dorssel** [comment]
@JohnBerg60 
I can reproduce this log when the WSL instance is shut down while a device is attached. It is an error report from `usbipd-win` itself, and (at least for the case I described) is normal. In my test, this does not stop the service itself and is intended behavior.

Can you determine what causes the error in your case? Is it WSL shutdown? Or something else. What I am looking for is a crash report from the Windows Service manager that explains why the service itself stopped.

**Comment by dorssel** [comment]
@JohnBerg60 
Ah, I see. Please run the server with verbose debug logging, see https://github.com/dorssel/usbipd-win/wiki/Troubleshooting. That should give you a crash report on the console.

**Comment by dorssel** [comment]
@JohnBerg60 
I've just finished a PR that may solve your problem. See #164, the installer is at https://github.com/dorssel/usbipd-win/actions/runs/1705631433. Could you give that a go?

**Comment by JohnBerg60** [comment]
I installed the update, and used it for a couple days. So far so good!

**Comment by Scrappers-glitch** [comment]
I just started the service manually:

![image](https://user-images.githubusercontent.com/60224159/193115763-4ed53844-3435-444e-8cab-c63ee319da6b.png)
